# Generated by Django 4.2.29 on 2026-03-15 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectiontask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='detection.detectiontask'),
        ),
    ]
