# Generated by Django 4.2.29 on 2026-03-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectiontask',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10),
        ),
    ]
